language: node_js

script:
  - node_modules/.bin/_mocha --compilers coffee:coffee-script/register
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
os:
  - linux
  - osx
